stages:
  - mirror
  - deploy

include:
  - component: gitlab.com/gabriel.chamon/ci-components/github-mirror@v1
    inputs:
      job_stage: mirror
  - component: gitlab.com/gabriel.chamon/ci-components/orisun-gitlab@v1
    inputs:
      job_name: sync_issues
      job_stage: deploy
      mode: sync
