hl.on("hyprland.start", function()
  hl.exec_cmd("pactl set-source-volume alsa_input.pci-0000_74_00.6.analog-stereo 25%")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("/usr/lib/kdeconnectd")
  hl.exec_cmd("/usr/bin/kdeconnect-indicator")
  hl.exec_cmd("hyprctl setcursor Breeze5 24")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("~/.config/hypr/scripts/launch-waybar.sh")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("wl-clip-persist --clipboard both")
  hl.exec_cmd("rm ~/.cache/cliphist/db")
  hl.exec_cmd("kitty --start-as=fullscreen", { workspace = "special:magic silent" })
  hl.exec_cmd("xhost +SI:localuser:root")
  hl.exec_cmd("archie applet")
end)
