.archie-python-quality:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.14-trixie-slim@sha256:bebc7d6de6dd015a483903461eaedea12805728be6f9a044ca7106a2f7e11ddf
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends gcc git jq libatomic1 libcairo2-dev libgirepository-2.0-dev pkg-config python3-dev gir1.2-gtk-4.0
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - uv sync --locked --group dev
  rules:
    - when: always

pytest:
  extends: .archie-python-quality
  script:
    - uv run pytest --cov=archie --cov-report=xml --cov-report=term
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

ruff:
  extends: .archie-python-quality
  script:
    - uv run ruff check src tests

pyright:
  extends: .archie-python-quality
  script:
    - uv run pyright src tests
